version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  streamlit:
    build:
      context: .
      dockerfile: ./streamlit/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./models:/app/models